# .goreleaser.yml
before:
  hooks:
    - mkdir -p internal
    - go mod tidy
    - go generate ./...
    - go install github.com/akavel/rsrc@latest
    - which rsrc
    - rm -rf ./dist

builds:
  - id: nowin
    env:
      - CGO_ENABLED=0
      - GO111MOULE=on
    goos:
      - linux
      - darwin
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    goarm:
      - '7'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/WindowsSov8forUs/go-kyutorin/version.Version={{ .Version }}
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: '386'
  - id: win
    env:
      - CGO_ENABLED=0
      - GO111MOULE=on
    goos:
      - windows
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    goarm:
      - '7'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/WindowsSov8forUs/go-kyutorin/version.Version={{ .Version }}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: binary

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-{{ .Commit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'